name:Python CI

#Trigger the workflow on any push to the main branch or pull request to the main branch
on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
        - main

jobs:
    test:
        runs-on: ubuntu-latest #container to run the job on eg ubuntu, windows, macos

        steps:
            #Step 1: Check out the code from the repository
            - name: Check out code
              uses: actions/checkout@v2

            #Step 2 : Set up Python
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            
            #Step 3: Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            #Step 4: Run tests
            - name: Run tests
              run: |
                # Run unit tests
                pytest --maxfail=1 --disable-warnings -q
